spring:
  application:
    name: ssew-core
  profiles:
    include: secrets
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      ssl:
        enabled: false
      timeout: 2000ms

  main:
    banner-mode: off
  web:
    resources:
      add-mappings: false

server:
  port: 9000

logging:
  level:
    com.singhtwenty2: DEBUG

