spring:
  application:
    name: ssew-core
  profiles:
    include: secrets
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      ssl:
        enabled: false
      timeout: 2000ms

  main:
    banner-mode: off
  web:
    resources:
      add-mappings: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  port: 9000

logging:
  level:
    com.singhtwenty2: DEBUG

sentry:
  dsn: https://ad18eb754e205240603dc689a13414d9@o4509932630441984.ingest.us.sentry.io/4509932658360320

  send-default-pii: true

  logging:
    enabled: true
    minimum-event-level: warn
    minimum-breadcrumb-level: info

  traces-sample-rate: 0.1

  environment: development

  release: ssew-core@0.0.1-SNAPSHOT

  enable-tracing: true

  debug: true

  tags:
    service: ssew-core
    version: 0.0.1-SNAPSHOT