spring:
  application:
    name: ssew-core
  profiles:
    include: secrets
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      ssl:
        enabled: false
      timeout: 2000ms

  main:
    banner-mode: off
  web:
    resources:
      add-mappings: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  port: 9000

logging:
  level:
    com.singhtwenty2: DEBUG



