#
# Copyright 2025 Aryan Singh
# Developer: Aryan Singh (@singhtwenty2)
# Portfolio: https://singhtwenty2.pages.dev/
# This file is part of SSEW E-commerce Backend System
# Licensed under MIT License
# For commercial use and inquiries: aryansingh.corp@gmail.com
# @author Aryan Singh (@singhtwenty2)
# @project SSEW E-commerce Backend System
# @since 2025
#

spring:
  application:
    name: commerce-service
  profiles:
    include: secrets
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  data:
    redis:
      ssl:
        enabled: false
      timeout: 2000ms

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  main:
    banner-mode: off
  web:
    resources:
      add-mappings: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  port: 9000

logging:
  level:
    com.singhtwenty2: DEBUG
    io.sentry: OFF

app:
  watermark:
    default-text: "Exclusive Product"
    enabled: true

sentry:
  dsn: https://ad18eb754e205240603dc689a13414d9@o4509932630441984.ingest.us.sentry.io/4509932658360320
  send-default-pii: true
  logging:
    enabled: true
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  traces-sample-rate: 0.01
  environment: development
  release: ssew-core@0.0.1-SNAPSHOT
  enable-tracing: true
  debug: false
  tags:
    service: ssew-core
    version: 0.0.1-SNAPSHOT

grpc:
  telemetry-service:
    host: localhost
    port: 9002