#
# Copyright 2025 SSEW Core Service
# Developer: Aryan Singh (@singhtwenty2)
# Portfolio: https://singhtwenty2.pages.dev/
# This file is part of SSEW E-commerce Backend System
# Licensed under MIT License
# For commercial use and inquiries: aryansingh.corp@gmail.com
# @author Aryan Singh (@singhtwenty2)
# @project SSEW E-commerce Backend System
# @since 2025
#

spring:
  application:
    name: ssew-core
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}
      ssl:
        enabled: false
      timeout: 2000ms
  main:
    banner-mode: off
  web:
    resources:
      add-mappings: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  port: 9000

logging:
  level:
    com.singhtwenty2: INFO

app:
  security:
    developer-secret: ${APP_SECURITY_DEVELOPER_SECRET}
  watermark:
    default-text: ${APP_WATERMARK_DEFAULT_TEXT:Exclusive Product}
    enabled: ${APP_WATERMARK_ENABLED:true}

jwt:
  secret: ${JWT_SECRET}

aws:
  region: ${AWS_REGION}
  s3:
    temp-bucket: ${AWS_S3_TEMP_BUCKET}
    temp-folder: ${AWS_S3_TEMP_FOLDER:temp}
    permanent-folder: ${AWS_S3_PERMANENT_FOLDER:permanent}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}