#
# Copyright 2025 Aryan Singh
# Developer: Aryan Singh (@singhtwenty2)
# Portfolio: https://singhtwenty2.pages.dev/
# This file is part of SSEW E-commerce Backend System
# Licensed under MIT License
# For commercial use and inquiries: aryansingh.corp@gmail.com
# @author Aryan Singh (@singhtwenty2)
# @project SSEW E-commerce Backend System
# @since 2025
#

spring:
  application:
    name: commerce-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl:
        enabled: false
      timeout: 3000ms
  main:
    banner-mode: off
  web:
    resources:
      add-mappings: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  port: ${SERVER_PORT:9000}

logging:
  level:
    com.singhtwenty2: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    io.sentry: OFF

app:
  security:
    developer-secret: ${APP_SECURITY_DEVELOPER_SECRET}
  watermark:
    default-text: ${APP_WATERMARK_DEFAULT_TEXT:Premium Quality}
    enabled: ${APP_WATERMARK_ENABLED:true}

jwt:
  secret: ${JWT_SECRET}

aws:
  region: ${AWS_REGION}
  s3:
    temp-bucket: ${AWS_S3_TEMP_BUCKET}
    temp-folder: ${AWS_S3_TEMP_FOLDER:temp}
    permanent-folder: ${AWS_S3_PERMANENT_FOLDER:permanent}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: false
  logging:
    enabled: true
    minimum-event-level: error
    minimum-breadcrumb-level: warn
  traces-sample-rate: 0.01
  environment: production
  release: ${APP_VERSION:ssew-core@1.0.0}
  enable-tracing: true
  debug: false
  tags:
    service: ssew-core
    version: ${APP_VERSION:1.0.0}

grpc:
  telemetry-service:
    host: ${GRPC_TELEMETRY-SERVICE_HOST:telemetry-service}
    port: ${GRPC_TELEMETRY-SERVICE_PORT:9002}